// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	service "github.com/lks-go/url-shortener/internal/service"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// MakeBatchShortURL provides a mock function with given fields: ctx, userID, urls
func (_m *Service) MakeBatchShortURL(ctx context.Context, userID string, urls []service.URL) ([]service.URL, error) {
	ret := _m.Called(ctx, userID, urls)

	if len(ret) == 0 {
		panic("no return value specified for MakeBatchShortURL")
	}

	var r0 []service.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []service.URL) ([]service.URL, error)); ok {
		return rf(ctx, userID, urls)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []service.URL) []service.URL); ok {
		r0 = rf(ctx, userID, urls)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []service.URL) error); ok {
		r1 = rf(ctx, userID, urls)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MakeShortURL provides a mock function with given fields: ctx, userID, url
func (_m *Service) MakeShortURL(ctx context.Context, userID string, url string) (string, error) {
	ret := _m.Called(ctx, userID, url)

	if len(ret) == 0 {
		panic("no return value specified for MakeShortURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, userID, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, userID, url)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Stats provides a mock function with given fields: ctx
func (_m *Service) Stats(ctx context.Context) (*service.StatsInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 *service.StatsInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*service.StatsInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *service.StatsInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.StatsInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// URL provides a mock function with given fields: ctx, id
func (_m *Service) URL(ctx context.Context, id string) (string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for URL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersURLs provides a mock function with given fields: ctx, userID
func (_m *Service) UsersURLs(ctx context.Context, userID string) ([]service.UsersURL, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UsersURLs")
	}

	var r0 []service.UsersURL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]service.UsersURL, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []service.UsersURL); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.UsersURL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
